bicicleta/urls.py
from django.urls import path
from .views import (criar_bicicleta, buscar_bicicleta, editar_bicicleta, deletar_bicicleta)

urlpatterns = [
    path('criar/', criar_bicicleta, name='criar_bicicleta'),
    path('', buscar_bicicleta, name='buscar_bicicleta'),
    path('<int:pk>/editar', editar_bicicleta, name='editar_bicicleta'),
    path('<int:pk>/deletar', deletar_bicicleta, name='deletar_bicicleta'),
]

cliente/urls.py
from django.urls import path
from .views import criar_cliente, buscar_cliente, editar_cliente, deletar_cliente

urlpatterns = [
    path('criar/', criar_cliente, name='criar_cliente'),
    path('', buscar_cliente, name='buscar_cliente'),
    path('<int:pk>/editar', editar_cliente, name='editar_cliente'),
    path('<int:pk>/excluir', deletar_cliente, name='deletar_cliente'),
]

moreno_admin/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servico/', include('servico.urls')),
    path('cliente/', include('cliente.urls')),
    path('bicicleta/', include('bicicleta.urls'))
]

servico/urls.py
from django.urls import path
from .views import criar_servico, buscar_servico, editar_servico, deletar_servico

urlpatterns = [
    path('criar/', criar_servico, name='criar_servico'),
    path('', buscar_servico, name='buscar_servico'),
    path('<int:pk>/editar', editar_servico, name='editar_servico'),
    path('<int:pk>/deletar', deletar_servico, name='deletar_servico'),
]

bicicleta/models.py
from django.db import models
from cliente.models import Cliente
from servico.models import Servico

class Bicicleta(models.Model):
  marca = models.CharField(max_length=200)
  modelo = models.CharField(max_length=200)
  cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
  servicos = models.ManyToManyField(Servico)
  def __str__(self):
    text ='{} - {}'.format(self.marca,self.modelo)
    return text

cliente/models.py
from django.db import models

class Cliente(models.Model):
    nomes = models.CharField(max_length=200, unique=True)
    cep = models.CharField(max_length=10)
    complemento = models.CharField(max_length=200)
    numero = models.CharField(max_length=10)
    telefone = models.CharField(max_length=19)
    def __str__(self):
        text = '{}'.format(self.nomes)
        return text

    

servico/models.py
from django.db import models

class Servico(models.Model):
  nome = models.CharField(max_length=200, unique=True)
  preco= models.FloatField(default=0.0)
  def __str__(self):
      return self.nome
  

bicicleta/forms.py
from django import forms
from django.forms import ModelForm 
from .models import Bicicleta

class BikeForm(forms.ModelForm):
  class Meta:
    model = Bicicleta
    fields = [
      'marca', 'modelo', 'cliente', 'servicos',
    ]

cliente/forms.py
from django import forms
from django.forms import ModelForm 
from .models import Cliente

class DadosForm(forms.ModelForm):
  class Meta:
    model = Cliente
    fields = [
      'nomes', 'cep', 'complemento', 'numero', 'telefone',
    ]

servico/forms.py
from django import forms
from django.forms import ModelForm 
from .models import Servico

class CadastroForm(forms.ModelForm):
  class Meta:
    model = Servico
    fields = [
      'nome', 'preco'
    ]

bicicleta/views.py
from django.shortcuts import render, redirect, get_object_or_404
import pdb;


from .models import Bicicleta
from .forms import BikeForm

def criar_bicicleta(request):
  form=BikeForm(request.POST or None)
  if form.is_valid():
    form.save()
    return redirect('buscar_bicicleta')
  return render(request, 'bicicleta/form_cadastro.html', {'form':form})

def buscar_bicicleta(request):
  data = Bicicleta.objects.all()
  return render(request, 'bicicleta/listagem.html', {'data':data})

def editar_bicicleta(request, pk):
  bicicleta = get_object_or_404(Bicicleta, pk=pk)
  form=BikeForm(request.POST or None, instance=bicicleta)
  if form.is_valid():
    form.save()
    return redirect('buscar_bicicleta')
  return render(request, 'bicicleta/form_cadastro.html', {'form':form})

def deletar_bicicleta(request, pk):
  bicicleta = get_object_or_404(Bicicleta, pk=pk)
  if request.method=='POST':
    bicicleta.delete()
    return redirect('buscar_bicicleta')
  return render(request, 'deletar_confirmar.html', {'object':bicicleta})

cliente/views.py
from django.shortcuts import render, redirect, get_object_or_404
import pdb;

from .models import Cliente
from .forms import DadosForm

def criar_cliente(request):
  form=DadosForm(request.POST or None)
  if form.is_valid():
    form.save()
    return redirect('buscar_cliente')
  return render(request, 'cliente/form_cadastro.html', {'form':form})

def buscar_cliente(request):
  data = Cliente.objects.all()
  return render(request, 'cliente/listagem.html', {'data':data})

def editar_cliente(request, pk):
  cliente = get_object_or_404(Cliente, pk=pk)
  form=DadosForm(request.POST or None, instance=cliente)
  if form.is_valid():
    form.save()
    return redirect('buscar_cliente')
  return render(request, 'cliente/form_cadastro.html', {'form':form})

def deletar_cliente(request, pk):
  cliente = get_object_or_404(Cliente, pk=pk)
  if request.method=='POST':
    cliente.delete()
    return redirect('buscar_cliente')
  return render(request, 'deletar_confirmar.html', {'object':cliente})

servico/views.py
from django.shortcuts import render, redirect, get_object_or_404
import pdb;


from .models import Servico
from .forms import CadastroForm

def criar_servico(request):
  form=CadastroForm(request.POST or None)
  if form.is_valid():
    form.save()
    return redirect('buscar_servico')
  return render(request, 'servico/form_cadastro.html', {'form':form})

def buscar_servico(request):
  data = Servico.objects.all()
  return render(request, 'servico/listagem.html', {'data':data})

def editar_servico(request, pk):
  servico = get_object_or_404(Servico, pk=pk)
  form=CadastroForm(request.POST or None, instance=servico)
  if form.is_valid():
    form.save()
    return redirect('buscar_servico')
  return render(request, 'servico/form_cadastro.html', {'form':form})

def deletar_servico(request, pk):
  servico = get_object_or_404(Servico, pk=pk)
  if request.method=='POST':
    servico.delete()
    return redirect('buscar_servico')
  return render(request, 'deletar_confirmar.html', {'object':servico})

templates/bicicleta/form_cadastro.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}
{% block breadcrumb %}
<div class="row">
  <div class="col-xl-12">
    <div class="page-title-box">
      <ol class="breadcrumb float-left">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/">Cadastros</a></li>
        {% if form.instance.pk %}
        <li class="breadcrumb-item active">Editar</li>
        {% else %}
        <li class="breadcrumb-item active">Novo</li>
        {% endif %}
      </ol>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
{% endblock %}
<!-- end row -->

{% block content %}

<div class="row">
  <div class="col-xl-12">
    <div class="card-box table-responsive">
      <h4 class="m-t-0 header-title"> Cadastro de Bicicleta </h4>
      <div class="tab-content p-0 bg-white">
        <div class="tab-pane active" id="home" role="tabpanel">
          <form class="" method="POST" action="" enctype="multipart/form-data"
            onsubmit="saveButton.disabled = true; return true;">
            {% csrf_token %}
            <div class="form-group row">
              <div class="col-8">
                <p>Marca</p>
                {{ form.marca }}
              </div>
              <div class="col-8">
                <p>Modelo</p>
                {{ form.modelo }}
              </div>
              <div class="col-8">
                <p>Cliente</p>
                {{ form.cliente }}
              </div>
              <div class="col-4">
                <p>Servicos</p>
                {{ form.servicos }}
              </div>
            </div>
            <button class="primaryAction btn btn-sm btn-success waves-effect waves-light"><span class="btn-label"><i
                  class="fa fa-check"></i></span>Salvar</button>
            <a onclick="history.back()"
              class="btn btn-primary btn-sm waves-effect waves-light dashboard-letter secondaryAction"><span
                class="btn-label"><i class="fa fa-arrow-left"></i></span>Voltar</button></a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block scripts %}

<script>
  $(document).ready(function () {
    var SPMaskBehavior = function (val) {
      return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
    },
      spOptions = {
        onKeyPress: function (val, e, field, options) {
          field.mask(SPMaskBehavior.apply({}, arguments), options);
        }
      };

    $('#id_telefone').mask(SPMaskBehavior, spOptions);
  });
</script>

<script>
  $(document).ready(function () {
    $("#id_data_nascimento").mask("99/99/9999");
    $("#id_data_diagnostico").mask("99/99/9999");
    $("#id_ano").mask("99/99/9999");
  });
</script>

{% endblock scripts %}

templates/bicicleta/listagem.html
{% extends "base.html" %}
{% load static i18n %}
{% block breadcrumb %}
<div class="row">
    <div class="col-xl-12">
        <div class="page-title-box">
            <ol class="breadcrumb float-left">
                <li class="breadcrumb-item"><a href="/"> Home </a></li>
                <li class="breadcrumb-item active"> Cadastros </li>
            </ol>
            <h4 class="page-title float-right">
              <a href="{% url 'criar_bicicleta' %}" class="btn btn-primary btn-sm waves-effect waves-light dashboard-letter secondaryAction"><span class="btn-label"><i class="fa fa-plus"></i></span>Novo</button></a>
            </h4>

            <div class="clearfix"></div>
        </div>
    </div>
</div>
{% endblock %}
<!-- end row -->

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
           <h4 class="m-t-0 header-title"><i class="fa fa-flag"></i> Bicicleta </h4>
              <p class="text-muted font-14 m-b-30">
              </p>
            <table id="datatable-buttons" class="table" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th width="220px">Marca</th>
                    <th width="200px">Modelo</th>
                    <th width="220px">Cliente</th>
                    <th width="200px">Servicos</th>
                    <th width="380px" class="text-right">Ações</th>
                </tr>
                </thead>
                <tbody>
                {% for bicicleta in data %}
                  <tr>
                      <td>{{bicicleta.marca}}</td>
                      <td>{{bicicleta.modelo}}</td>
                      <td>{{bicicleta.cliente}}</td>
                      <td>
                        {% for servicos in bicicleta.servicos.values %}

                          <span>{{servicos.nome}}, </span>
                        {% endfor %}
                      </td>
                      <td  class="text-right">
                        <a href="{% url 'editar_bicicleta' bicicleta.id %}"  class="btn btn-success btn-sm waves-effect waves-light"><i class="fa fa-paint-brush"></i> Editar</a>
                        <a href="{% url 'deletar_bicicleta' bicicleta.id %}" class="btn btn-danger btn-sm waves-effect waves-light"><i class="fa fa-times"></i> Excluir</a>
                      </td>
                  </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
      </div>
    </div>
    
{% endblock content %}

{% block scripts %}

<!-- Required datatable js -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>
<!-- Buttons examples -->
<script src="{% static 'plugins/datatables/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables/jszip.min.js' %}"></script>
<script src="{% static 'plugins/datatables/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/datatables/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables/buttons.print.min.js' %}"></script>

<!-- Responsive examples -->
<script src="{% static 'plugins/datatables/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables/responsive.bootstrap4.min.js' %}"></script>

<script type="text/javascript">
    $(document).ready(function() {

        //Buttons examples
        var table = $('#datatable-buttons').DataTable({
            columnDefs: [
              {orderable: false, targets: [4]}
            ],
            lengthChange: false,
            language: {
              processing: "Carregando...",
              search: "Pesquisar:",
              info: "Mostrando de _START_ a _END_ de _TOTAL_ registros",
              infoEmpty: "",
              infoFiltered: "(filtrando de _MAX_ registros no total)",
              infoPostFix: "",
              loadingRecords: "Carregando...",
              zeroRecords: "Nenhum registro encontrado",
              emptyTable: "Nenhum registro",
              paginate: {
                  first: "Primeiro",
                  previous: "Anterior",
                  next: "Próximo",
                  last: "Último"
              },
            },
            buttons: ['excel', 'pdf']
        });

        table.buttons().container()
                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
    } );

</script>
{% endblock scripts %}

templates/cliente/form_cadastro.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}
{% block breadcrumb %}
<div class="row">
  <div class="col-xl-12">
    <div class="page-title-box">
      <ol class="breadcrumb float-left">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/">Cadastros</a></li>
        {% if form.instance.pk %}
        <li class="breadcrumb-item active">Editar</li>
        {% else %}
        <li class="breadcrumb-item active">Novo</li>
        {% endif %}
      </ol>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
{% endblock %}
<!-- end row -->

{% block content %}

<div class="row">
  <div class="col-xl-12">
    <div class="card-box table-responsive">
      <h4 class="m-t-0 header-title"> Cadastro de Cliente </h4>
      <div class="tab-content p-0 bg-white">
        <div class="tab-pane active" id="home" role="tabpanel">
          <form class="" method="POST" action="" enctype="multipart/form-data"
            onsubmit="saveButton.disabled = true; return true;">
            {% csrf_token %}
            <div class="form-group row">
              <div class="col-8">
                <p>Nomes </p>
                {{ form.nomes }}
              </div>
              <div class="col-8">
                <p>CEP</p>
                {{ form.cep }}
              </div>
              <div class="col-8">
                <p>Complemento</p>
                {{ form.complemento }}
              </div>
              <div class="col-8">
                <p>Numero</p>
                {{ form.numero }}
              </div>
              <div class="col-4">
                <p>Telefone</p>
                {{ form.telefone }}
              </div>
            </div>
            <button class="primaryAction btn btn-sm btn-success waves-effect waves-light"><span class="btn-label"><i
                  class="fa fa-check"></i></span>Salvar</button>
            <a onclick="history.back()"
              class="btn btn-primary btn-sm waves-effect waves-light dashboard-letter secondaryAction"><span
                class="btn-label"><i class="fa fa-arrow-left"></i></span>Voltar</button></a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block scripts %}

<script>
  $(document).ready(function () {
    var SPMaskBehavior = function (val) {
      return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
    },
      spOptions = {
        onKeyPress: function (val, e, field, options) {
          field.mask(SPMaskBehavior.apply({}, arguments), options);
        }
      };

    $('#id_telefone').mask(SPMaskBehavior, spOptions);
  });
</script>

<script>
  $(document).ready(function () {
    $("#id_data_nascimento").mask("99/99/9999");
    $("#id_data_diagnostico").mask("99/99/9999");
    $("#id_ano").mask("99/99/9999");
  });
</script>

{% endblock scripts %}

templates/cliente/listagem.html
{% extends "base.html" %}
{% load static i18n %}
{% block breadcrumb %}
<div class="row">
    <div class="col-xl-12">
        <div class="page-title-box">
            <ol class="breadcrumb float-left">
                <li class="breadcrumb-item"><a href="/"> Home </a></li>
                <li class="breadcrumb-item active"> Cadastros </li>
            </ol>
            <h4 class="page-title float-right">
              <a href="{% url 'criar_cliente' %}" class="btn btn-primary btn-sm waves-effect waves-light dashboard-letter secondaryAction"><span class="btn-label"><i class="fa fa-plus"></i></span>Novo</button></a>
            </h4>

            <div class="clearfix"></div>
        </div>
    </div>
</div>
{% endblock %}
<!-- end row -->

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
           <h4 class="m-t-0 header-title"><i class="fa fa-flag"></i> Cliente </h4>
              <p class="text-muted font-14 m-b-30">
              </p>
            <table id="datatable-buttons" class="table" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th width="220px">nomes</th>
                    <th width="200px">cep</th>
                    <th width="220px">complemento</th>
                    <th width="200px">numero</th>
                    <th width="220px">telefone</th>
                    <th width="380px" class="text-right">Ações</th>
                </tr>
                </thead>
                <tbody>
                {% for cliente in data %}
                  <tr>
                    <td>{{cliente.nomes}}</td>
                    <td>{{cliente.cep}}</td>
                    <td>{{cliente.complemento}}</td>
                    <td>{{cliente.numero}}</td>
                    <td>{{cliente.telefone}}</td>
                      <td  class="text-right">
                        <a href="{% url 'editar_cliente' cliente.id %}" class="btn btn-success btn-sm waves-effect waves-light"><i class="fa fa-paint-brush"></i> Editar</a>
                        <a href="{% url 'deletar_cliente' cliente.id %}"  class="btn btn-danger btn-sm waves-effect waves-light"><i class="fa fa-times"></i> Excluir</a>
                      </td>
                  </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
      </div>
    </div>
    
{% endblock content %}

{% block scripts %}

<!-- Required datatable js -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>
<!-- Buttons examples -->
<script src="{% static 'plugins/datatables/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables/jszip.min.js' %}"></script>
<script src="{% static 'plugins/datatables/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/datatables/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables/buttons.print.min.js' %}"></script>

<!-- Responsive examples -->
<script src="{% static 'plugins/datatables/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables/responsive.bootstrap4.min.js' %}"></script>

<script type="text/javascript">
    $(document).ready(function() {

        //Buttons examples
        var table = $('#datatable-buttons').DataTable({
            columnDefs: [
              {orderable: false, targets: [4]}
            ],
            lengthChange: false,
            language: {
              processing: "Carregando...",
              search: "Pesquisar:",
              info: "Mostrando de _START_ a _END_ de _TOTAL_ registros",
              infoEmpty: "",
              infoFiltered: "(filtrando de _MAX_ registros no total)",
              infoPostFix: "",
              loadingRecords: "Carregando...",
              zeroRecords: "Nenhum registro encontrado",
              emptyTable: "Nenhum registro",
              paginate: {
                  first: "Primeiro",
                  previous: "Anterior",
                  next: "Próximo",
                  last: "Último"
              },
            },
            buttons: ['excel', 'pdf']
        });

        table.buttons().container()
                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
    } );

</script>
{% endblock scripts %}

templates/deletar_confirmar.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}
{% block breadcrumb %}
<div class="row">
    <div class="col-xl-12">
        <div class="page-title-box">
            <ol class="breadcrumb float-left">
                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="">Cadastros</a></li>
                <li class="breadcrumb-item active">Excluir {{ object.nome }} </li>
            </ol>

            <div class="clearfix"></div>
        </div>
    </div>
</div>
{% endblock %}
<!-- end row -->

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
           <h4 class="m-t-0 header-title"> Deletar </h4>
          <p class="text-muted font-14 m-b-30"></p>
        <form class="" method="POST" action="" onsubmit="saveButton.disabled = true; return true;">
          {% csrf_token %}
            <div class="form-group row">
                <div class="col-12">
                  Você tem certeza que deseja excluir "{{ object.nome }}" ?
                </div>
            </div>
          <div class="form-group text-left row m-t-10">
              <div class="col-12">
                <button class="primaryAction btn btn-sm btn-danger waves-effect waves-light"><span class="btn-label"><i class="fa fa-times"></i></span>Excluir</button>
                <a onclick="history.back()" class="btn btn-primary btn-sm waves-effect waves-light dashboard-letter secondaryAction"><span class="btn-label"><i class="fa fa-arrow-left"></i></span>Voltar</button></a>
              </div>
          </div>
        </form>
      </div>
    </div>
{% endblock content %}

templates/servico/form_cadastro.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}
{% block breadcrumb %}
<div class="row">
  <div class="col-xl-12">
    <div class="page-title-box">
      <ol class="breadcrumb float-left">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/">Cadastros</a></li>
        {% if form.instance.pk %}
        <li class="breadcrumb-item active">Editar</li>
        {% else %}
        <li class="breadcrumb-item active">Novo</li>
        {% endif %}
      </ol>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
{% endblock %}
<!-- end row -->

{% block content %}

<div class="row">
  <div class="col-xl-12">
    <div class="card-box table-responsive">
      <h4 class="m-t-0 header-title"> Cadastro de Serviço </h4>
      <div class="tab-content p-0 bg-white">
        <div class="tab-pane active" id="home" role="tabpanel">
          <form class="" method="POST" action="" enctype="multipart/form-data"
            onsubmit="saveButton.disabled = true; return true;">
            {% csrf_token %}
            <div class="form-group row">
              <div class="col-8">
                <p>Nome do Serviço</p>
                {{ form.nome }}
              </div>
              <div class="col-4">
                <p>Preço do Serviço</p>
                {{ form.preco }}
              </div>
            </div>
            <button class="primaryAction btn btn-sm btn-success waves-effect waves-light"><span class="btn-label"><i
                  class="fa fa-check"></i></span>Salvar</button>
            <a onclick="history.back()"
              class="btn btn-primary btn-sm waves-effect waves-light dashboard-letter secondaryAction"><span
                class="btn-label"><i class="fa fa-arrow-left"></i></span>Voltar</button></a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block scripts %}

<script>
  $(document).ready(function () {
    var SPMaskBehavior = function (val) {
      return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
    },
      spOptions = {
        onKeyPress: function (val, e, field, options) {
          field.mask(SPMaskBehavior.apply({}, arguments), options);
        }
      };

    $('#id_telefone').mask(SPMaskBehavior, spOptions);
  });
</script>

<script>
  $(document).ready(function () {
    $("#id_data_nascimento").mask("99/99/9999");
    $("#id_data_diagnostico").mask("99/99/9999");
    $("#id_ano").mask("99/99/9999");
  });
</script>

{% endblock scripts %}

templates/servico/listagem.html
{% extends "base.html" %}
{% load static i18n %}
{% block breadcrumb %}
<div class="row">
    <div class="col-xl-12">
        <div class="page-title-box">
            <ol class="breadcrumb float-left">
                <li class="breadcrumb-item"><a href="/"> Home </a></li>
                <li class="breadcrumb-item active"> Cadastros </li>
            </ol>
            <h4 class="page-title float-right">
              <a href="{% url 'criar_servico' %}" class="btn btn-primary btn-sm waves-effect waves-light dashboard-letter secondaryAction"><span class="btn-label"><i class="fa fa-plus"></i></span>Novo</button></a>
            </h4>

            <div class="clearfix"></div>
        </div>
    </div>
</div>
{% endblock %}
<!-- end row -->

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
           <h4 class="m-t-0 header-title"><i class="fa fa-flag"></i> Serviços </h4>
              <p class="text-muted font-14 m-b-30">
              </p>
            <table id="datatable-buttons" class="table" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th width="220px">Nome</th>
                    <th width="200px">preço</th>
                    <th width="380px" class="text-right">Ações</th>
                </tr>
                </thead>
                <tbody>
                {% for servico in data %}
                  <tr>
                      <td>{{servico.nome}}</td>
                      <td>{{servico.preco}}</td>
                      <td  class="text-right">
                        <a href="{% url 'editar_servico' servico.id %}" class="btn btn-success btn-sm waves-effect waves-light"><i class="fa fa-paint-brush"></i> Editar</a>
                        <a href="{% url 'deletar_servico' servico.id %}" class="btn btn-danger btn-sm waves-effect waves-light"><i class="fa fa-times"></i> Excluir</a>
                      </td>
                  </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
      </div>
    </div>
    
{% endblock content %}

{% block scripts %}

<!-- Required datatable js -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>
<!-- Buttons examples -->
<script src="{% static 'plugins/datatables/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables/jszip.min.js' %}"></script>
<script src="{% static 'plugins/datatables/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/datatables/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables/buttons.print.min.js' %}"></script>

<!-- Responsive examples -->
<script src="{% static 'plugins/datatables/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables/responsive.bootstrap4.min.js' %}"></script>

<script type="text/javascript">
    $(document).ready(function() {

        //Buttons examples
        var table = $('#datatable-buttons').DataTable({
            columnDefs: [
              {orderable: false, targets: [4]}
            ],
            lengthChange: false,
            language: {
              processing: "Carregando...",
              search: "Pesquisar:",
              info: "Mostrando de _START_ a _END_ de _TOTAL_ registros",
              infoEmpty: "",
              infoFiltered: "(filtrando de _MAX_ registros no total)",
              infoPostFix: "",
              loadingRecords: "Carregando...",
              zeroRecords: "Nenhum registro encontrado",
              emptyTable: "Nenhum registro",
              paginate: {
                  first: "Primeiro",
                  previous: "Anterior",
                  next: "Próximo",
                  last: "Último"
              },
            },
            buttons: ['excel', 'pdf']
        });

        table.buttons().container()
                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
    } );

</script>
{% endblock scripts %}